### ISSUE TITLE
Information / Disclaimer & Conditions of use - Back button cannot be seen

### ISSUE THREAD

**Issue by workerbee22** [Western-Health-Covid19-Collaboration/wh_covid19_app#195]
Bug where the 'back' button in top left on the AppBa is there, but is colored white on white. Functions correctly but cannot be seen.

Note this is probably a theming issue, so avoid hard coding a color: property. Instead investigate the theme color being used.

![image](https://user-images.githubusercontent.com/5154664/78611905-53ddb180-78ab-11ea-8e29-82df487a0e9a.png)

**Comment by rockgecko-development** [comment]
Back button is showing for me on info screen in latest build. Refer screenshots in https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/pull/194

I guess the fix for disclaimer screen would be to conditionally set `AppBar.iconTheme: Styles.appBarIconTheme,` based on if this is the first time disclaimer is showing (and you aren't allowed to hit the back button) or not.

**Comment by sallychung** [comment]
✅ v1.0.114
![IMG_904F85D761EA-1](https://user-images.githubusercontent.com/12321678/78888585-3ffd9f80-7aa5-11ea-8193-93819c595232.jpeg)
