### ISSUE TITLE
Messaging Overlap between Disclaimer 'top messages', Full Disclaimer and TestFlight release 'management' text

### ISSUE THREAD

**Issue by maks** [Western-Health-Covid19-Collaboration/wh_covid19_app#237]

**Comment by workerbee22** [comment]
We currently have 3 separate pieces of content trying to do similar things:
- Description of the app's audience and role, added late to top of Disclaimer. Personally I think it is better in an Onboarding experience.
- Disclaimer text 
- New Management required paragraphs required in TestFlight release notes

All are doing the same or similar things. Need to reconcile these and be clear about the goal of each and remove the duplicated messages, or else live with constant changes forever.

Apple also seemed to prefer the approach for production App Store release of a Disclaimer AND (as in addition to) 'prominent' messaging about audience and intended use of the app NPT being for comsumers.

**Comment by lukesleeman** [comment]
Good call out - I've applied the `Medic` label and assigned this one over to @greggmiller , though I guess for the most part we can just hash out the details over in slack 👍

**Comment by greggmiller** [comment]
I agree that some of the duplications on information may seem unnecessary. However, it is more reinforcement by repetition under these circumstances so that it is 100% clear who the target audience is. The risk if we aren't quite clear Ron this message is substantial - the app gets pulled under COVID restrictions and considerable setback on timeline.

I think the best order from here would be...
On entering the app...

Disclaimer  
->
Onboarding

TestFlight release notes to be streamlined as we go along.

**Comment by lukesleeman** [comment]
It sounds like this is something we need to resolve for the Version 1 relese - I'm assigning it to that milestone

**Comment by lukesleeman** [comment]
When we are updating the disclaimer, we need to modify the disclaimer, so that under the "Please keep in mind section" it says: "WAC19 gathers analytics and crash data which is used to improve the app. For more information and to opt out, go to information > settings"

The build out of the settings screen is being tracked as part of #301

**Comment by workerbee22** [comment]
@greggmiller is currently working through a document for app content (like disclaimer) and the app store listings. The goal is to get the right content in the right places.

**Comment by lukesleeman** [comment]
> When we are updating the disclaimer, we need to modify the disclaimer, so that under the "Please keep in mind section" it says: "WAC19 gathers analytics and crash data which is used to improve the app. For more information and to opt out, go to information > settings"
> 
> The build out of the settings screen is being tracked as part of #301

I'm making the updates as part of this PR: https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/pull/315

**Comment by lukesleeman** [comment]
Just checking in here - @greggmiller I know you have a new disclaimer text - are you going to integrate it yourself, or did you want to put it in here and we can get one of the other flutter devs on it?

**Comment by greggmiller** [comment]
@lukesleeman  I have completed the document with Mike for this and we have finalised disclaimer and simplified the onboarding screen. So we can close this now I think. Might be something that needs to be revisited and simplified  further down the track

**Comment by workerbee22** [comment]
btw. This was the feedback from Western Health legal representative:

![image](https://user-images.githubusercontent.com/5154664/82398935-5846de00-9a97-11ea-99c3-a7b67cc826bd.png)
