### ISSUE TITLE
resuable_infographic_page widget in view to have multi-page alternative

### ISSUE THREAD

**Issue by greggmiller** [Western-Health-Covid19-Collaboration/wh_covid19_app#252]
There are several infographics which are multi-page that we would like to include in future versions of the app.

Would it be possible for the reusable_infographic_page widget to be modified or an alternative created so that it can be used for this purpose. Ideally the only main modification for this would be that it would be scrollable (up/down) and would preferably have some information on it as to how many pages total the infographic consists of (e.g. 1/3, 2/3, 3/3) so that the user knows which page they are on.

It is likely a multi=page widget would be used for several items planned for the cross-skilling list.

I think @yimingc2 created this widget originally and wonder if her or @workerbee22 would have a good handle on how this could be done? 😄

**Comment by workerbee22** [comment]
PageView() was my first thought, with a page indicator. 

But I think we also need to look at the infographics themselves more closely:
- They are constructed as single pages and are useful when I assume they are printed as a single sides A4 page. As in actual physical paper.
- They shown multiple 'steps' usually in a short process.

If we use a PageView, each 'step' can have an image and/or text, can pinch-to-zoom etc. Also much easier on mobile, because only a single step is on screen at once and so can be bigger.

Then the user just swipes between each step.

It is also a very common pattern on both Android and iOS.

The idea is the existing assets would be the master/'approved' content, but we would just present it better in the ap for a mobile screen. Because at the moment I find it hard/impossible to read much of the text or see the pictures on my phone (and mine is a large screen device).

**Comment by greggmiller** [comment]
Hi @workerbee22  I agree, I think having the ability to break the infographics down to steps that we can slide between would be extremely useful.
It would be the ideal solution.
This is perhaps a slightly separate issue to the multipage infographic widget as I still think there would be some demand for the multi-page widget so the infographics would be there as a reference. 

In terms of poor image quality/graininess, the source material for nearly all infographics we use come from these 2 sites:

Safe Airway Society (mainly intubation): 
https://asa.org.au/wordpress/wp-content/uploads/SAS-Covid-19-Infographics.pdf

Royal North Shore Cognitive aids (extubation):
https://www.rnsascar.com/covid-19

Both of those societies have given us permission to use their infographics.

**Comment by lukesleeman** [comment]
Based on our discussions in the call this evening, it sounds like @workerbee22 will do some prototyping tomorrow on possible solutions.

@kimngyn did provide this video as a possible example:
https://youtu.be/lrMCjIYpnjg

In the video they have a number of cards with images on them - then you tap each one and get it fullscreen

**Comment by greggmiller** [comment]
That video looks an incredible way to break down infographics 😄

**Comment by workerbee22** [comment]
Ok mocked something up based on the **Extubation** we have in the app already. The infographic for it is this image/pdf: 

https://c14cdbb8-fa6f-468d-93e6-86b26d7dbbf8.filesusr.com/ugd/7ddf74_9b0003df894542688b48b65e7ecaf920.pdf

Mocked a quick and very rough PageView alternative, where we break down the content away from a single page that we 'zoom' into a more mobile friendly result. Advantages are:

- larger images and more space for guidance
- no need to zoom to read
- many other opportunities to improve with other tap gestures, more information, links etc.

Preview ... remember its quick and rough (took about 1.5 hours) so images are fuzzy, could be bigger, could be tappable .... but you get the idea:

![infographics paging](https://user-images.githubusercontent.com/5154664/79427835-a4ba7c00-8008-11ea-8cc4-044cc7670b0e.gif)

**Comment by workerbee22** [comment]
I wish we had imagery as sexy as Nike sneakers 🤣

**Comment by greggmiller** [comment]
This looks incredible @workerbee22 🙌 💯

**Comment by lukesleeman** [comment]
So - we discussed this in detail during tonights call.  Basically we think there are a few issues mixed in here:

1. Why do we have the infographics in here?  Is it because we have a legal/medical requirement to show the original source?  Or will medical staff find them useful?  Can they be altered and if so how much?

2. How do we display infographics with multiple pages?

3. How can we break up and better format information on mobile screens?  A lot of the existing screens _are already_ better, more mobile specific versions of the infographics.  In other cases some of the readability and graphic nature of the infographics have been lost.

Point number 2 should be fairly easy to address with some input from the designers, however point 1, and 3 also need some serious thought.

After discussion we decided to try and get some more feedback from the medical staff at WH and find out exactly what their needs are for infographics.  Hopefully once that is resolved, we can design a more appropriate solution.  I've moved the issue back to @greggmiller and changed it over to `Medic`

**Comment by lukesleeman** [comment]
After discussing with @greggmiller it seems we will need to add a number of infographics for V1 which have multiple pages, so we will at least need to do mult-page infographics.

**Comment by lukesleeman** [comment]
So, I've moved this one _out_ of the Version 1 milestone.  As we discussed during our call we will just track the new infographics via issue #284 , which will include the multi page infographics.

This issue can remain about breaking up and better formatting infographics to mobile screens

**Comment by lukesleeman** [comment]
We are now displaying the complete PDFs in the app, which kind of solves the issue of showing multi page infographics.  I'm closing down this issue.
