### ISSUE TITLE
Emoji alignments in Your Welfare and Cross Skilling

### ISSUE THREAD

**Issue by sallychung** [Western-Health-Covid19-Collaboration/wh_covid19_app#282]
Emojis for each cell is not aligned with it’s text.
This affects all screens across You Welfare, Proning and ALS/BLS

Image highlights a few screens that stands out the most.

There’s also a vertical alignment under Proning. ６6 x staff available for proning

![Copy changes 010](https://user-images.githubusercontent.com/12321678/80266615-203ebc00-86e0-11ea-897d-6869bb83ecae.jpeg)

**Comment by workerbee22** [comment]
Again need to move away from emojis as per [issue 185](https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/issues/185)

**Comment by yimingc2** [comment]
The space seems to be built into the font. It only happens for emoji but not the text.
This might be related: https://github.com/flutter/flutter/issues/28894

<img width="361" alt="Screen Shot 2020-04-25 at 10 19 31 pm" src="https://user-images.githubusercontent.com/14011195/80279788-0d110800-8743-11ea-9f7b-e5fbfb177e4d.png">

It's properly aligned on Android though. I don't know what the solution for it. @workerbee22 @maks 
Maybe a different font could help? We should probably use proper icons instead of emojis?

**Comment by maks** [comment]
I'd agree, given we have great designers helping us, using actual icons would be much better

**Comment by sallychung** [comment]
✅ v1.0.160

![IMG_0076](https://user-images.githubusercontent.com/12321678/80368551-4165ff00-88d0-11ea-8b3a-651f423ebfce.PNG)
![IMG_0077](https://user-images.githubusercontent.com/12321678/80368555-42972c00-88d0-11ea-9846-296d1f279860.PNG)
