### ISSUE TITLE
List all the contributors

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#289]
At the moment the Acknowledgements and references screen has this:

![image](https://user-images.githubusercontent.com/902252/80274994-d37bd500-8721-11ea-9cf5-e8becd19a1d1.png)

However it doesn't actually list the names of everybody!  We would like to somehow include the names of all the contributors in the app.

We could possibly put them into the Acknowledgements and References screen.  Another alternative would be to include them or link them from the information screen where it says "Built with ❤️ by a band of volunteers

**Comment by cjmlgrto** [comment]
I was originally hesitant at first to add the "Contributors" inside the app because it sounds tedious having to manually update that list every time a new volunteer for the project rolls in. It'd be great if this could be automated somehow 🤔 

## Updated - Information Screen

![Info](https://user-images.githubusercontent.com/1712450/80293511-5a24c680-87a3-11ea-9cae-31774b86e5fe.png)

* Much more condensed Information screen
* Added "Last Updated Date" under the app version number
* Contributors now added inside the "Acknowledgement and References" screen

**Comment by lukesleeman** [comment]
As we have designs, I'm going to close this issue and just wrap all the changes into issue #288 🙂

**Comment by sallychung** [comment]
✅ v1.0.173
