### ISSUE TITLE
Build out the intubation guide screen

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#37]
From the main menu there is a button which takes you to the intubation step by step guidance screen.  That screen is currently **really** basic.

**We need to build build out a detailed version of the intubation step by step guidance screen**

@greggmiller Can you please provide some information in this issue on what should be in this section?  Once that is done assign the issue to Marc Edwards.

@marcedwards Once greg has provided info, can you provide some design guidance in this issue in on how it should look.  Once this is done, can you label this issue as "Ready for Dev" so that one of the devs can pick it up.

**Comment by greggmiller** [comment]
(For a bit of lay person insight, intubation is the prcoess of placing a patient in a drug-induced coma and then inserting a breathing tube from the mouth into the trachea. In Covid19 patients it is high risk as it is an "Aerosol-generating procedure" meaning it puts us at risk as lots of virus gets in the air and can infect us. We want to make sure both we and our junior medical staff get it right)...


Please refer to Source document: SAS COVID 19 infographics 1 2.pdf

This again a step by step with 6 steps:
1. Planning
2. Prepare
3. PPE
4. Pre-oxygenation
5. Perform
6. Post-ETT

Each of these steps will have the 4-6 bullet points of information next to them
So it might require some type of scroll screen

The full information would be:
1. Planning
Intervene early
Negative pressure room (if possible)
Meticulous airway assessment
Discuss ventilation plan (Protective lung ventilation).

2. Prepare
Assemble airway team (Airway operator, Airway Assistant, Team Leader, Door Runner, Outside room Runner.)
Use COVID-19 Intubation tray
Ensure Viral filter and etCO2 in ventilation circuit
Share airway strategy

3. PPE
Hand hygiene
Donning: HH>Gown>Mask>Eye Protection>Hat>HH>Gloves
Spotter to perform "Buddy check" to ensure correct PPE fit
Airway operator double glove

4. Pre-oxygenation
45-degree head-up position
Pre-oxygentate with Face mask using 2 hands
Ensure sqyare etCO2 waveform
Avoid apnoiec oxygenation techniques due to aerolisaiton risk

5. Perform
Use VL; use the screen (indirect view_ to maximise operator distance
Modified RSI technique
No ventilation prior to intubation unless for rescue oxygenation
Wait 60s for paralysis to take effect - avoid triggering cough.


6. Post-ETT
Inflate cuff BEFORE initiaitng ventilation and monitor cuff pressures to avoid leak
Remove outer gloves, dispose of airway equipment in sealed bag
Doffing: Gloves>Gown>HH>Hat>eye Protection>Mask>HH
Use a spotter
Debrief and share lessons



 * The above steps are unlikely to change, but the bullet points may. As our knowledge of COVID19 increases we will refine our advise on safest intubation technique*

**Comment by greggmiller** [comment]
@galtaforce Very keen if you have the opportunity to review the above, ensure it complies with current WH policy (I believe there have been recent changes) and amend/modify as you recommend.
@benblackman Please feel free to provide feedback also!

**Comment by galtaforce** [comment]
Looks to comply as far as I can see. All following the SAS guidelines. There may be the addition of hooded coverall PPE so perhaps we could just direct people to the PPE section to make sure only the most recent information is shown.

**Comment by benblackman** [comment]
Agreed with redirection to the PPE section

I think David Bramley mentioned that we don't want people to think that the hooded coverall is a necessary condition of AGP care once it arrives, as stock levels may require us to return to standard gowns. Should we present it as an alternative option? I guess more of a question for #32 ?

**Comment by kimngyn** [comment]
[SAS COVID 19 infographics.pdf](https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/files/4385546/SAS.COVID.19.infographics.pdf)

**Comment by lukesleeman** [comment]
Yeah, so there has been a little bit of confusion between what this issue is and waht is covered by #39 .  Just to be clear, this is Page 1 of SAS COVID 19 infographics.pdf.  Basically this:

![image](https://user-images.githubusercontent.com/902252/77730417-dae18d00-7054-11ea-96d0-8da4eb7310f4.png)

**Comment by greggmiller** [comment]
Yes, @lukesleeman Apologies for the confusion!

**Comment by lukesleeman** [comment]
@Mattro has posted designs in zeplin, and they look great!

![image](https://user-images.githubusercontent.com/902252/77847281-c4c7fe00-7207-11ea-9a22-f140f355aa6e.png)

@Mattro or @marcedwards  is this one `Ready for dev`?

**Comment by benblackman** [comment]
🔥

Awesome work @Mattro

**Comment by lukesleeman** [comment]
Ok @rockgecko-development  - as discussed in tonights call, I've moved this issue over to ready for dev, and assigned you :-)   

Ignore the infographic in the above screenshot ☝️ , but all the other screens with the ✅ , etc are for you to build :-) 

Have a chat to @ericjiang97 who has already build a similar screen for the checklist
